networks:
  default:
    external: true
    name: trendco-net

services:
  ximxim-db:
    image: mariadb
    container_name: ximxim-db
    hostname: ximxim-db
    restart: always
    volumes:
      - /web/sites/trendco.dev/ximxim/mysql/:/var/lib/mysql
      - /web/sites/trendco.dev/ximxim/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - default

  ximxim-express:
    image: registry.gitlab.com/trendco/test/ximxim:latest
    container_name: ximxim-express
    hostname: ximxim-express
    restart: unless-stopped
    links:
      - ximxim-db:mysql
    networks:
      - default
    depends_on:
      - ximxim-db
    environment:
      TZ: 'Europe/Moscow'
    blkio_config:
      device_read_bps:
        - path: /dev/vda
          rate: 1048576
      device_read_iops:
        - path: /dev/vda
          rate: 100
      device_write_bps:
        - path: /dev/vda
          rate: 1048576
      device_write_iops:
        - path: /dev/vda
          rate: 100
